2024-12-04 22:26:31,054 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\hua\Desktop\Обучение Python-разработчик\Testing\tests_12_4.py", line 68, in test_run
    second = Runner(324, 5)
             ^^^^^^^^^^^^^^
  File "C:\Users\hua\Desktop\Обучение Python-разработчик\Testing\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-04 22:26:31,055 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\hua\Desktop\Обучение Python-разработчик\Testing\tests_12_4.py", line 58, in test_walk
    first = Runner('Alex', -5)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\hua\Desktop\Обучение Python-разработчик\Testing\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
